fix: Remove `Meta` from `Model` (#215)
Pyright 1.1.339 enabled reportIncompatibleVariableOverride=true as part of new default "standard" mode.

https://github.com/microsoft/pyright/releases/tag/1.1.339

This leads to

> error: "Meta" overrides symbol of same name in class "Model"

At runtime, models do not have `Meta` if it's not defined, so it's safe to remove it.